# pandas file reading

In [9]:
import pandas as pd
import pandas as pd

In [10]:
df=pd.read_csv('usa_mercedes_benz_prices.csv')

In [11]:
df.head(5)

,Name,Mileage,Rating,Review Count,Price
0,2021 Mercedes-Benz A-Class A 220 4MATIC,"29,636 mi.",3.9,"1,800","$30,900"
1,2022 Mercedes-Benz AMG SL 63 Base,"5,540 mi.",4.7,"1,239","$139,999"
2,2022 Mercedes-Benz AMG SL 63 Base,"4,890 mi.",4.7,"1,239","$132,999"
3,2020 Mercedes-Benz AMG E 53 Base 4MATIC,"29,746 mi.",4.8,752,"$58,587"
4,2021 Mercedes-Benz AMG GLS 63 Base 4MATIC,"32,631 mi.",5.0,"1,502","$95,990"

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2429 entries, 0 to 2428
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          2429 non-null   object
 1   Mileage       2429 non-null   object
 2   Rating        2135 non-null   float64
 3   Review Count  2398 non-null   object
 4   Price         2429 non-null   object
dtypes: float64(1), object(4)
memory usage: 95.0+ KB

In [13]:
df.describe()

            Rating
count  2135.000000
mean      4.533724
std       0.386506
min       2.100000
25%       4.400000
50%       4.600000
75%       4.800000
max       5.000000

# csv

In [15]:
from io import StringIO, BytesIO

In [16]:
data=('col1,col2,col3\n'
      'x,y,1\n'
      'a,b,2\n'
      'c,d,3\n')

In [17]:
type(data)

str

In [21]:
df=pd.read_csv(StringIO(data))

In [22]:
df

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [20]:
#read from specific columns
pd.read_csv(StringIO(data),usecols=['col1','col3'])

  col1  col3
0    x     1
1    a     2
2    c     3

In [28]:
# chnage the colum datatypes

df=pd.read_csv(StringIO(data),dtype={'col3': int,'col2': 'string'})

In [30]:
df['col1'][0]

'x'

In [34]:
type(df['col3'][2])

numpy.int64

In [35]:
##cheak the all datatypes of the columns
df.dtypes

col1            object
col2    string[python]
col3             int64
dtype: object

In [36]:
data=('a,b,c\n'
      '4,apple,bat,\n'
      '8,orange,cow,')

In [ ]:
pd.read_csv(StringIO(data)) #here 4 and 8 it take it like index

        a    b   c
4   apple  bat NaN
8  orange  cow NaN

In [38]:
pd.read_csv(StringIO(data),index_col=False)

   a       b    c
0  4   apple  bat
1  8  orange  cow